version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: fullstack-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: fullstack_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - fullstack-network

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: fullstack-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8081:8081"
    networks:
      - fullstack-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local

networks:
  fullstack-network:
    driver: bridge
